CREATE TABLE IF NOT EXISTS CUSTOMER
( CUSTOMER_ID INT,
FIRST_NAME STRING,
MIDDLE_NAME STRING,
LAST_NAME STRING,
DOB STRING,
GENDER STRING,
NATIONALITY STRING,
IDENTIFIER_TYPE STRING,
IDENTIFIER STRING,
MARITAL_STATUS STRING,
OCCUPATION STRING,
AVG_FAMILY_SIZE INT,
INCOME_LEVEL STRING,
DATE_ONBOARDED STRING
)
ROW FORMAT
        DELIMITED
        FIELDS TERMINATED BY ','
        ESCAPED BY '\\\\'
LOCATION 'hdfs://centos7-1.0102wnbqrtjuzfcm5j10ce4rjb.bx.internal.cloudapp.net:8020/dev/final/customer' tblproperties("skip.header.line.count"="1"); 




CREATE TABLE IF NOT EXISTS ADDRESS
( ADDRESS_ID INT,
ADDRESS_TYPE STRING,
ADDRESS1 STRING,
ADDRESS2 STRING,
ADDRESS3 STRING,
CITY STRING,
STATE STRING,
COUNTRY STRING,
ZIPCODE INT,
PHONE INT,
EMAIL STRING,
FAX INT,
CUSTOMER_ID INT
)
ROW FORMAT
        DELIMITED
        FIELDS TERMINATED BY ','
        ESCAPED BY '\\\\'
LOCATION 'hdfs://centos7-1.0102wnbqrtjuzfcm5j10ce4rjb.bx.internal.cloudapp.net:8020/dev/final/address' 
tblproperties("skip.header.line.count"="1"); 


CREATE TABLE IF NOT EXISTS PRODUCT
(PRODUCT_ID INT,
PRODUCT_NAME STRING,
PRODUCT_TYPE STRING,
PRODUCT_DESCRIPTION STRING,
ISSUE_DATE STRING,
VALID_TILL_DATE STRING,
ACCOUNT_STATUS STRING,
CREDIT_CARD_LIMIT INT,
INTEREST_RATE STRING,
TENURE INT,
SERVICE_CHARGES INT,
CUSTOMER_ID INT,
FD_PRINCIPAL_AMOUNT INT,
LOAN_COLLATERAL_VALUE INT,
LOAN_AMOUNT INT
)
ROW FORMAT
        DELIMITED
        FIELDS TERMINATED BY ','
        ESCAPED BY '\\\\'
LOCATION 'hdfs://centos7-1.0102wnbqrtjuzfcm5j10ce4rjb.bx.internal.cloudapp.net:8020/dev/final/product' 
tblproperties("skip.header.line.count"="1"); 





CREATE TABLE IF NOT EXISTS TRANSACTIONS
(TRANSACTION_ID INT,
CUSTOMER_ID INT,
PRODUCT_ID INT,
MERCHANT_NAME STRING,
TRANSACTION_DESCRIPTION STRING,
TRANSACTION_AMOUNT INT,
TYPE_DEPOSIT_WITHDRAWAL STRING,
TRANSACTION_DATE STRING,
CHANNEL STRING
) ROW FORMAT
      DELIMITED
      FIELDS TERMINATED BY ','
      ESCAPED BY '\\\\'
LOCATION 'hdfs://centos7-1.0102wnbqrtjuzfcm5j10ce4rjb.bx.internal.cloudapp.net:8020/dev/final/transactions' 
tblproperties("skip.header.line.count"="1"); 




CREATE TABLE IF NOT EXISTS CUSTOMER_360
( CUSTOMER_ID INT,
FIRST_NAME STRING,
MIDDLE_NAME STRING,
LAST_NAME STRING,
DOB STRING,
GENDER STRING,
NATIONALITY STRING,
IDENTIFIER_TYPE STRING,
IDENTIFIER STRING,
MARITAL_STATUS STRING,
OCCUPATION STRING,
AVG_FAMILY_SIZE INT,
INCOME_LEVEL STRING,
DATE_ONBOARDED STRING,
ADDRESS_ID INT,
ADDRESS_TYPE STRING,
ADDRESS1 STRING,
ADDRESS2 STRING,
ADDRESS3 STRING,
CITY STRING,
STATE STRING,
COUNTRY STRING,
ZIPCODE INT,
PHONE INT,
EMAIL STRING,
FAX INT,
PRODUCT_ID INT,
PRODUCT_NAME STRING,
PRODUCT_TYPE STRING,
PRODUCT_DESCRIPTION STRING,
ISSUE_DATE STRING,
VALID_TILL_DATE STRING,
ACCOUNT_STATUS STRING,
CREDIT_CARD_LIMIT INT,
INTEREST_RATE STRING,
TENURE INT,
SERVICE_CHARGES INT,
FD_PRINCIPAL_AMOUNT INT,
LOAN_COLLATERAL_VALUE INT,
LOAN_AMOUNT INT,
TRANSACTION_ID INT,
MERCHANT_NAME STRING,
TRANSACTION_DESCRIPTION STRING,
TRANSACTION_AMOUNT INT,
TYPE_DEPOSIT_WITHDRAWAL STRING,
TRANSACTION_DATE STRING,
CHANNEL:STRING,
AGE INT
)
ROW FORMAT
        DELIMITED
        FIELDS TERMINATED BY ','
        ESCAPED BY '\\\\'
LOCATION 'hdfs://centos7-1.0102wnbqrtjuzfcm5j10ce4rjb.bx.internal.cloudapp.net:8020/dev/final/customer_360' 
tblproperties("skip.header.line.count"="1"); 






